eureka:
  instance:
    hostname: ${APP_URL:localhost}
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: patients
        uri: lb://patient-producer
        predicates:
        - Path=/api/patient/**